### PR TITLE
Project files for .NET Framework 4.0

### PR DESCRIPTION
**Pull request by vtortola**
These are the solution and project files that build the source using .NET Framework v4.0

### CODE REVIEW

**Comment by romerod** [comment]
I created a new branch and made some adjustments.

Could you test the prerelease package http://www.nuget.org/packages/Baseclass.Contrib.SpecFlow.Selenium.NUnit/1.3.2-tn40support2 ?

If you change the pull requests target branch to feature/net40support it should be marked as merged

**Comment by vtortola** [comment]
How can I change the target branch?

**Comment by romerod** [comment]
Oh, i was reading about this last time, didn't realize it was a feature request...

Could you test the prerelease package?

**Comment by vtortola** [comment]
I think it is a pull request. Sorry, I am kind of new in GitHub :)

I am under heavy fire at the moment but I promise I will try during today or tomorrow.

Cheers.

**Comment by vtortola** [comment]
It works good, thanks for that!

**Pull request closed without merging**
